CREATE DATABASE IF NOT EXISTS horeca;
USE horeca;

CREATE TABLE IF NOT EXISTS Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    MotDePasse VARCHAR(255) NOT NULL,
    Telephone VARCHAR(20),
    Role VARCHAR(50) NOT NULL DEFAULT 'Client',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (Email)
);

CREATE TABLE IF NOT EXISTS Terrains (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    Nom VARCHAR(255) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    Disponible BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Reservations (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    UserId INT NOT NULL,
    TerrainId CHAR(36) NOT NULL,
    DateDebut DATETIME NOT NULL,
    DateFin DATETIME NOT NULL,
    Prix DECIMAL(10,2) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (TerrainId) REFERENCES Terrains(Id) ON DELETE CASCADE,
    INDEX idx_user_id (UserId),
    INDEX idx_terrain_id (TerrainId)
);

CREATE TABLE IF NOT EXISTS Employes (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Poste VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Plannings (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    EmployeId CHAR(36) NOT NULL,
    DateDebut DATETIME NOT NULL,
    DateFin DATETIME NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (EmployeId) REFERENCES Employes(Id) ON DELETE CASCADE,
    INDEX idx_employe_id (EmployeId)
);

CREATE TABLE IF NOT EXISTS CartesFidelite (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    UserId INT NOT NULL UNIQUE,
    Points INT NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    CarteFideliteId CHAR(36) NOT NULL,
    Points INT NOT NULL,
    Description VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CarteFideliteId) REFERENCES CartesFidelite(Id) ON DELETE CASCADE,
    INDEX idx_carte_fidelite_id (CarteFideliteId)
);

-- Migration pour base existante : ajouter colonne Role si absente
-- ALTER TABLE Users ADD COLUMN Role VARCHAR(50) NOT NULL DEFAULT 'Client';
